version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/AgentOrchestrator"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/src/AgentOrchestrator-python"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
