#!/usr/bin/env python3
"""Rewrite links that point outside docs/ to absolute GitHub URLs.

Markdown under ``docs/`` links to things that live outside it — source files,
``AGENTS.md``, ``.github/`` config. Those work when browsing the repository on
GitHub, but on the generated site there is no such page, so MkDocs reports them
as broken.

Absolute GitHub URLs work in both contexts, so this rewrites them in place.
Idempotent: already-absolute links are left alone.

Run from the repository root::

    python3 scripts/rewrite_doc_links.py          # apply
    python3 scripts/rewrite_doc_links.py --check  # report only, non-zero if work needed
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = "https://github.com/vicperdana/aigenius-copilotsdk-s5ep2"
BLOB = f"{REPO}/blob/main"
TREE = f"{REPO}/tree/main"

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

LINK = re.compile(r"(!?\[[^\]]*\]\()([^)]+)(\))")


def rewrite(target: str, page: Path) -> str:
    """Rewrite one link target if it escapes docs/."""
    if target.startswith(("http://", "https://", "#", "mailto:")):
        return target

    path, _, anchor = target.partition("#")
    anchor = f"#{anchor}" if anchor else ""
    if not path:
        return target

    resolved = (page.parent / path).resolve()

    try:
        resolved.relative_to(DOCS)
        return target  # still inside docs/ — leave relative
    except ValueError:
        pass

    try:
        rel = resolved.relative_to(ROOT)
    except ValueError:
        return target  # outside the repo entirely; leave alone

    base = TREE if resolved.is_dir() else BLOB
    return f"{base}/{rel.as_posix()}{anchor}"


def main() -> int:
    check_only = "--check" in sys.argv
    changed: list[str] = []

    for page in sorted(DOCS.rglob("*.md")):
        if page.name == "index.md":
            continue  # generated by build_index.py
        original = page.read_text(encoding="utf-8")
        updated = LINK.sub(
            lambda m: m.group(1) + rewrite(m.group(2), page) + m.group(3), original
        )
        if updated != original:
            changed.append(str(page.relative_to(ROOT)))
            if not check_only:
                page.write_text(updated, encoding="utf-8")

    verb = "would rewrite" if check_only else "rewrote"
    print(f"{verb} {len(changed)} file(s)")
    for c in changed:
        print(f"  {c}")

    return 1 if (check_only and changed) else 0


if __name__ == "__main__":
    raise SystemExit(main())
